python -m src.run_decision_transformer \
    --exp_name MiniGrid-DoorKey-8x8-v0-Test \
    --trajectory_path trajectories/0efb210c-6f04-4478-8ae1-e2c4ab147e1d.gz \
    --d_model 128 \
    --n_heads 2 \
    --d_mlp 256 \
    --n_layers 1 \
    --learning_rate 0.0001 \
    --batch_size 128 \
    --train_epochs 500 \
    --test_epochs 10 \
    --n_ctx 3 \
    --pct_traj 1 \
    --weight_decay 0.001 \
    --seed 1 \
    --wandb_project_name DecisionTransformerInterpretability-Dev \
    --test_frequency 100 \
    --eval_frequency 100 \
    --eval_episodes 5 \
    --initial_rtg -1 \
    --initial_rtg 0 \
    --initial_rtg 1 \
    --prob_go_from_end 0.1 \
    --eval_max_time_steps 1000 \
    --track True
